# Uncomment this line to define a global platform for your project
# platform :ios, '7.0'
inhibit_all_warnings!
target 'CleverFarm' do

pod "AFNetworking", "~> 2.0"
pod "MagicalRecord"
pod 'MBProgressHUD', '~> 0.8'

end
